name: Prod Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        working-directory: ./client
        run: npm ci

      - name: Linting
        working-directory: ./client
        run: npm run lint

      - name: Build
        working-directory: ./client
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel deploy ${{ github.event.inputs.environment == 'prod' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./client
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
